### ISSUE TITLE
The Asynchronous Programming in Rust Book

### ISSUE THREAD

**Issue by crlf0710** [rust-lang-nursery/net-wg#9]
Maybe it should be made an official guide to using rustlang on asynchronous programming.

**Comment by killercup** [comment]
FTR, you can currently read the book here https://aturon.github.io/apr/ and the sources live at https://github.com/aturon/apr

**Comment by aturon** [comment]
Yes, my hope is for this to become official -- and actually for it to be a collaborative project of this working group.

It's been on hold until we sort out the initial async/await story, though.

**Comment by aturon** [comment]
Closing this in favor of finer-grained issues. I plan to move the book into this repo, ultimately.
